<?xml version="1.0" encoding="UTF-8"?>
<!-- Tests compiled with Criterion v2.3.3 -->
<testsuites name="Criterion Tests" tests="6" failures="4" errors="1" disabled="0">
  <testsuite name="dangerous_add" tests="6" failures="4" errors="1" disabled="0" skipped="0" time="0.000">
    <testcase name="test_passing" assertions="0" status="PASSED" time="0.000">
    </testcase>
    <testcase name="test_passed" assertions="0" status="PASSED" time="0.000">
    </testcase>
    <testcase name="test_failing_2" assertions="0" status="FAILED" time="0.000">
      <failure type="assert" message="0 assertion(s) failed."></failure>
    </testcase>
    <testcase name="test_failing_1" assertions="0" status="FAILED" time="0.000">
      <failure type="assert" message="0 assertion(s) failed."></failure>
    </testcase>
    <testcase name="test_fail_2" assertions="0" status="ERRORED" time="0.000">
      <error type="crash" message="The test crashed." />    </testcase>
    <testcase name="test_fail_1" assertions="0" status="FAILED" time="0.000">
      <failure type="assert" message="0 assertion(s) failed."></failure>
    </testcase>
  </testsuite>
</testsuites>
